services:
  frontend:
    build: ./frontend
    container_name: t_frontend
  backend:
    build: ./backend
    container_name: t_backend
    expose:
      - "5000"
  nginx:
    image: nginx:alpine
    container_name: quote_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
