
version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: quote_frontend
  backend:
    build: ./backend
    container_name: quote_backend
    expose:
      - "5000"
  nginx:
    image: nginx:alpine
    container_name: quote_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8085:80"
    depends_on:
      - frontend
      - backend
